### ISSUE TITLE
PHP Fatal error:  Can't inherit abstract function

### ISSUE THREAD

**Issue by SchumacherFM** [SchumacherFM/Anonygento#1]
Hi Cyrill,

I have seen that you have recently published an extension to anonyimize a Magento database. Since this is a tool that seems very useful  I wanted to play with it and review it. But it does not seem to work. Here are the issues I have encountered when running shell/anonygento.php:

PHP Fatal error:  Can't inherit abstract function SchumacherFM\Anonygento\Model\Zend\Console\Prompt\PromptInterface::show() (previously declared abstract in 
SchumacherFM\Anonygento\Model\Zend\Console\Prompt\AbstractPrompt) in 
/var/www/optimize/app/code/community/SchumacherFM/Anonygento/Model/Zend/Console/Prompt/AbstractPrompt.php on line 24
PHP Stack trace:
PHP   1. {main}() /var/www/optimize/shell/anonygento.php:0
PHP   2. Mage_Shell_Anonygento->run() /var/www/optimize/shell/anonygento.php:243
PHP   3. Mage_Shell_Anonygento->_runAnonymization() /var/www/optimize/shell/anonygento.php:87
PHP   4. SchumacherFM_Anonygento_Model_Console_Console->getModelZf2() /var/www/optimize/shell/anonygento.php:151
PHP   5. SchumacherFM_Anonygento_Model_Autoload_Zf2->autoload() /var/www/optimize/app/code/community/SchumacherFM/Anonygento/Model/Autoload/Zf2.php:0
PHP   6. require() /var/www/optimize/app/code/community/SchumacherFM/Anonygento/Model/Autoload/Zf2.php:39
PHP   7. SchumacherFM_Anonygento_Model_Autoload_Zf2->autoload() /var/www/optimize/app/code/community/SchumacherFM/Anonygento/Model/Autoload/Zf2.php:0
PHP   8. require() /var/www/optimize/app/code/community/SchumacherFM/Anonygento/Model/Autoload/Zf2.php:39
PHP   9. SchumacherFM_Anonygento_Model_Autoload_Zf2->autoload() /var/www/optimize/app/code/community/SchumacherFM/Anonygento/Model/Autoload/Zf2.php:0
PHP  10. require() /var/www/optimize/app/code/community/SchumacherFM/Anonygento/Model/Autoload/Zf2.php:39

This seems to be a ZF2 bug, see https://github.com/zendframework/zf2/issues/2899 . Patched it and moved on, but maybe you should include this patch in the extension. Then I got:

PHP Fatal error:  Uncaught exception 'Mage_Core_Exception' with message 'csv file for data (Email) not found!
/var/www/optimize/app/code/community/SchumacherFM/Anonygento/data/en_US/Email.csv
' in /var/www/optimize/app/Mage.php:594
Stack trace:
#0 /var/www/optimize/app/code/community/SchumacherFM/Anonygento/Model/Random/AbstractWeird.php(220): Mage::throwException('csv file for da...')
#1 /var/www/optimize/app/code/community/SchumacherFM/Anonygento/Model/Random/AbstractWeird.php(68): SchumacherFM_Anonygento_Model_Random_AbstractWeird->_loadFile('Email')
#2 /var/www/optimize/app/code/community/SchumacherFM/Anonygento/Model/Random/Customer.php(29): SchumacherFM_Anonygento_Model_Random_AbstractWeird->_construct()
#3 /var/www/optimize/lib/Varien/Object.php(112): SchumacherFM_Anonygento_Model_Random_Customer->_construct()
#4 /var/www/optimize/app/code/core/Mage/Core/Model/Config.php(1348): Varien_Object->__construct(Array)
#5 /var/www/optimize/app/Mage.php(462): Mage_Core_Model_Config->getModelInstance('schumacherfm_an...', Array)

 in /var/www/optimize/app/Mage.php on line 59

This is because I switched to US. I guess you have ran all tests on german locale, but most of the people are on en locale, it would be a good idea to have it working for it too. I fixed it by copying Email.csv in en_US. Then I got:

PHP Fatal error:  Call to undefined method Mage_Sales_Model_Resource_Quote::getDefaultAttributes() in /var/www/optimize/app/code/core/Mage/Eav/Model/Config.php on line 429
PHP Stack trace:
PHP   1. {main}() /var/www/optimize/shell/anonygento.php:0
PHP   2. Mage_Shell_Anonygento->run() /var/www/optimize/shell/anonygento.php:243
PHP   3. Mage_Shell_Anonygento->_runAnonymization() /var/www/optimize/shell/anonygento.php:87
PHP   4. Mage_Shell_Anonygento->_runAnonymizationReal() /var/www/optimize/shell/anonygento.php:158
PHP   5. SchumacherFM_Anonygento_Model_Console_Console->getModel() /var/www/optimize/shell/anonygento.php:172
PHP   6. Mage::getModel() /var/www/optimize/app/code/community/SchumacherFM/Anonygento/Model/Console/Console.php:54
PHP   7. Mage_Core_Model_Config->getModelInstance() /var/www/optimize/app/Mage.php:462
PHP   8. Varien_Object->__construct() /var/www/optimize/app/code/core/Mage/Core/Model/Config.php:1348
PHP   9. SchumacherFM_Anonygento_Model_Anonymizations_Abstract->_construct() /var/www/optimize/lib/Varien/Object.php:112
PHP  10. SchumacherFM_Anonygento_Model_Anonymizations_Abstract->_setMappings() /var/www/optimize/app/code/community/SchumacherFM/Anonygento/Model/Anonymizations/Abstract.php:45
PHP  11. SchumacherFM_Anonygento_Model_Random_Mappings->getMapping() /var/www/optimize/app/code/community/SchumacherFM/Anonygento/Model/Anonymizations/Abstract.php:92
PHP  12. Mage_Eav_Model_Config->getAttribute() /var/www/optimize/app/code/community/SchumacherFM/Anonygento/Model/Random/Mappings.php:97

I gave up here. Note that I am using the Magento sample data as a test dataset on Magento  CE 1.7.0.2.

I'd like to see the extension working and review it. Let me know when you think this is stable.

Thanks,
P

**Comment by SchumacherFM** [comment]
Fixed
